{
			clientToken: 'pub5876b7c09839ad3b8e73e96ad0d38588',
			applicationId: 'e03701b7-d955-4ca2-a121-e7f5d505b2e7',
			site: 'datadoghq.com',
			sessionSampleRate: 100,
			trackUserInteractions: true,
			service: 'shopist-web-ui',
			version: rumVersion,
			env: 'prod',
			allowedTracingUrls: [process.env.shopistApiUrl],
			startSessionReplayRecordingManually: true,
			sessionReplaySampleRate: 100,
			allowUntrustedEvents: true,
			defaultPrivacyLevel: 'mask-user-input'
			}