# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9437c267c60f1c80c5ea6784bbcdad0eba23aadf31d3059668bb2f39561e0352bb7c3f56a1b695912fe02cdb0751b378f767010e5511b174d53c9bc84c4a1a77

test:
  secret_key_base: 7604b55066e8ad7fe352be823f5ede3bd1cd06f42af9c17e7e5e35419ad56fa11ed3bcfa2eb6ddf950b8b8f7a3778799fae992e3073d98dd28421100ff8498fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
